### ISSUE TITLE
Windows Installer does not work either

### ISSUE THREAD

**Issue by ghost** [nasa/NTL-Asteroid-Data-Hunter#12]
Having had no luck installing and running ADH on a MAC, I tried downloading the Windows Version to a VM on my Mac and it failed just as spectacularly.

Again its getting can't write to directory errors on installation, when you take the apostrophe out of the Folder name it installs on a Docs Folder (won't install in Programs Folder), but still fails to run with a broad range of Server errors most of which seem to be tied up with ...... org.eclipse.jetty.server.handler ..... in the end it is getting a http Error 500.

**Comment by rashid-sial** [comment]
@astroswanny, what error did you receive when installing on a mac? I have had (and other users) no issues with mac.

Removing the apostrophe shouldn't change anything, and having it shouldn't affect anything either.

Can you uninstall / delete all directories and re-install using the latest code + user guide? Please see topcoder.com/asteroids

**Comment by ghost** [comment]
It comes back with Permission Denied as it tries to write the "NASA's" directory.

Reading the instructions again it seems there is a documentation error. In your install guide it says supported MAC is 10.10.x, I was going off your  Website that says MAC 10.2.x is supported. You might want to clear that up. 

So perhaps its just a case of Yosemite support apostrophes in path names (which is seriously BAD PRACTICE in coding) And 10.2 doesn't.

**Comment by rashid-sial** [comment]
Apologies, the download page has been updated. You can rename the install folder to whatever you see fit - and the app will still function. Are you running 10.2? That might be the primary reason you can't install the app.

**Comment by ghost** [comment]
Rashid,

Thanks, I am on MAC OS 10.7.2 4G of RAM.  (for the MAC version)

For a proper Release Map you would need:

Supported OS
Supported Browser versions
Supported Java Version
Supported Fusion VM versions (or alternatives) if you are running on a
Windows VM

I have uninstalled and re-installed several times on both the MAC installer
and the windows installer on the VM.

Neither work, so I am guessing its the 10.10.x issue. Its somewhat baffling
why you would design it to work only on Yosemite. I gather you might be
tapping into some of the new features of Yosemite.

Very keen for this to work...... I'll keep trying.

Regards
Peter

**Comment by rashid-sial** [comment]
Try this:
1. Create a folder on your desktop and call it "ADH"
2. Uninstall the app
3. Re-install the app, and set the install path to the folder you created on your desktop

Please let me know how it goes.
