### ISSUE TITLE
Java local install

### ISSUE THREAD

**Issue by jmrp12345** [nasa/NTL-Asteroid-Data-Hunter#20]
do you need Java installed on your local computer to run Asteroid Data Hunter

**Comment by jankeromnes** [comment]
Hi @jmrp12345! In theory you **won't need** to install Java locally, because all necessary binaries (including `java` for Mac / Ubuntu, or `java.exe` for Windows) are included in the installation bundles you can find on the [topcoder page](http://www.topcoder.com/asteroids/asteroiddatahunter/).

**Comment by jmrp12345** [comment]
Jan - thanks for the reply - since I was having "backend issue" error messages trying to run ADH(as have many others) I was wondering if a local Java installation made any difference - I am not aware of any fixes for this issue yet? -  Bob

Date: Thu, 18 Jun 2015 11:10:35 -0700
