### ISSUE TITLE
Waiting for the ubuntu version

### ISSUE THREAD

**Issue by Murazaki** [nasa/NTL-Asteroid-Data-Hunter#3]
Just to notify you that we're looking forward to it :)

**Comment by parejadan** [comment]
SAMEEEEEEE

**Comment by rashid-sial** [comment]
Still working on this - please hold tight :)

**Comment by astrochoupe** [comment]
I don't understand the difficulty to adapt it. It's just a Java webapp, no ? A JRE, an application server, a WAR and it's done, no ? I think Unix users can install it by hands.

**Comment by astrochoupe** [comment]
I see a detector.exe file. I think that's the main difficulty to port for linux... I think you must compile this executable for linux.

**Comment by parejadan** [comment]
I am interested in this project, maybe I can help contribute for the Linux port?

**Comment by rashid-sial** [comment]
I have a linux version - it's currently being tested. I'm aiming to release it this week. Please hold tight.

**Comment by olebole** [comment]
@rsial2 I would recommend to upload it to Debian as well. If it is in Debian, it would be automatically be part of Ubuntu, so one could install it as any other application, without any difficulty. This would make it much easier to install and keeping up-to-date.
Please contact me if you have any questions on this.

**Comment by rashid-sial** [comment]
A version of the app has been posted for Linux Ubuntu. If you'd like try it on Debian, you're more than welcome too :)

**Comment by Murazaki** [comment]
Thanks a lot for this version !

Some feedback from the installation :
- The files in the zip file were all at chmod 444 (I think they were set like this before being compressed). We need executable rights to launch the files (I did a chmod -R 755 ./\* to fix it)
- The menu link didn't show up on my computer (but I'm using elementary OS. It should be visible if it is on Ubuntu).
- The 8080 port is already used by a lot of other apps (like development servers ; Bitnami for instance)

Some good improvements too :
- A debian package
- A Webview (instead of using the browser) ?

**Comment by olebole** [comment]
For a Debian package, it would probably be useful to have it under the hood of the Debian Astronomy team ([Mailing list](https://lists.debian.org/debian-astro/)). In principle, it may be packaged and maintained directly by the author, @rsial2 , but anyone else could volunteer as well. 
You should in any case make sure that it follows the [Debian Policy](https://www.debian.org/doc/debian-policy/). Also, the debian specific files (`debian/` subdirectory) should be maintained not in the original git repository, but in the Debian one (hosted at [Alioth](https://alioth.debian.org/)), to enable other members of the team to participate.
