### ISSUE TITLE
This directory can not be written... (install issue)

### ISSUE THREAD

**Issue by sergiourraswift** [nasa/NTL-Asteroid-Data-Hunter#6]
Hello,

I running the ADHunter installer as administrator, but I can´t install it. I'm getting this message:

"This directory can not be written. Please choose another directory".

I'm able to install anything in any folder but SDHunter installer.

Win 7 - 64 bits

Any clue will be appreciated.

**Comment by rashid-sial** [comment]
Try creating a folder on your desktop, and then in the Installer, set the install path to that new folder on the desktop.
