### ISSUE TITLE
Uninstaller does not work

### ISSUE THREAD

**Issue by chainshaw** [nasa/NTL-Asteroid-Data-Hunter#7]
Attempting to run uninstaller.jar using javaw on Windows 7 does nothing. Running through the console produces no output.

![uninstall](https://cloud.githubusercontent.com/assets/929008/6752129/0cfccab2-cee2-11e4-8368-b71281a7649e.PNG)

**Comment by rashid-sial** [comment]
Double click the installer (\Uninstaller\uninstaller.jar) and it'll launch a GUI that'll help you uninstall the app.

**Comment by chainshaw** [comment]
Double-clicking did not launch the uninstaller. I was eventually able to launch it using "java -jar uninstaller.jar" from the command line.

**Comment by rashid-sial** [comment]
Do you know what version of Java you have installed?
