### ISSUE TITLE
Mac installation issue

### ISSUE THREAD

**Issue by mrmillares** [nasa/NTL-Asteroid-Data-Hunter#8]
I've completed the installation following the steps, but in the last one when the file "start.bat" has to be dragged on Terminal this alert appeared:

-bash: /Applications/NASA's Asteroid Data Hunter/start.bat: Permission denied
MacBookProMrMillares:~ mrmillares$ 

Any suggestion to solve it?

**Comment by rashid-sial** [comment]
It should be "start.sh", there was a mistake in the user guide. I just fixed it. Thanks for finding this!

**Comment by mrmillares** [comment]
Almost succeeded, but not. Now this:

Automatic deployment tool - Start
TCSASSEMBLER

Unable to find any JVMs matching version "(null)".

No Java runtime present, try --request to install.
JAVA_HOME=
warurl=/Applications/NASA's Asteroid Data Hunter/asteroid/hunter.war
applicationpath=/Applications/NASA's Asteroid Data Hunter
/Applications/NASA's Asteroid Data Hunter/start.sh: line 32: /bin/java: No such file or directory

**Comment by rashid-sial** [comment]
Please try this:
1. Delete the Asteroid Data Hunter folder from your Applications directory
2. Install the latest version of Java: java.com
3. Re-install the app.

Please let me know how it goes.

**Comment by mrmillares** [comment]
I did it all, but unfortunately the same alert message appears.

**Comment by rashid-sial** [comment]
Please go to https://www.java.com/en/download/installed.jsp?detect=jre&try=1 - this page will then show you what version of Java you have installed. And if you don't have the latest version which is Version 8 Update 40, please upgrade, restart your browser and attempt to launch the app again. Please let me know how it goes.

**Comment by mrmillares** [comment]
Yes, the Mac (v10.10.2) is running the latest version of Java (Version 8 Update 40).
In spite of the updating the message still appears.

**Comment by rashid-sial** [comment]
I am sorry about the issues you're experiencing - since this is now an open source project, we're working on the plan for ongoing support and maintenance. You'll probably need to wait until the next version is ready because I am unable to reproduce the error you're experiencing.

**Comment by mrmillares** [comment]
Thank you for the help anyway!

**Comment by cruisin2501** [comment]
On first extraction, none of the executables in the jre/bin directory are marked executable by default for me, so this needs a `chmod +x *` before anything happens. Also, the included `asteroid-installer-mac.jar` is referenced as `asteroid-installer-linux.jar` in the bash script (typo?).

Now I need to figure out this error message: 
`Error occurred during initialization of VM
Unable to find JVM location at $JAVA_HOME`

**Comment by cruisin2501** [comment]
If you actually have java installed, you can install using `java -jar asteroid-installer-mac.jar` and it will work.
